repos:
  - repo: local
    hooks:
      - id: replace-username-paths
        name: Replace $USER with user
        entry: python3 hooks/scripts/replace_username.py
        language: system
        pass_filenames: true
        types: [text]
