[config.custom_colors]
red = { color = "#f13c40", blend = true }
green = { color = "#41c257", blend = true }
blue = { color = "#0e85f0", blend = true }
mint = { color = "#07c2ac", blend = true }
teal = { color = "#02bbc5", blend = true }
cyan = { color = "#03b9db", blend = true }
indigo = { color = "#5b55e6", blend = true }
purple = { color = "#bd30d4", blend = true }
pink = { color = "#ed3053", blend = true }
yellow = { color = "#edc005", blend = true }
orange = { color = "#fb8d2c", blend = true }
brown = { color = "#a57d5a", blend = true }
black = { color = "#000000", blend = true }
white = { color = "#ffffff", blend = true }

[config]

version_check = false

[templates.niri]
input_path = '~/.config/matugen/templates/niri-colors.kdl'
output_path = '~/.config/niri/config/colors.kdl'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/config/colors.conf'
post_hook = 'if pgrep -x hyprland;then hyprctl reload;fi'

# [config.wallpaper] # Blazing fast and beautiful
# command = "hyprctl"
# arguments = ["hyprpaper", "reload", ","]
# set = false

# [config.wallpaper] # Animated nad nice llok
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = false

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
# `post_hook` is not needed because waybar handles it using `reload_style_on_change`
# post_hook = 'pkill waybar;setsid -f waybar >/dev/null 2>&1'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'if pgrep -x swaync >/dev/null 2>&1;then swaync-client -rs;fi'

[templates.swayosd]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swayosd/colors.css'
post_hook = 'if pgrep -x swayosd-server >/dev/null 2>&1;then pkill swayosd-server;setsid -f swayosd-server >/dev/null 2>&1;fi'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/settings/colors.rasi'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
# post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'
post_hook = '~/.config/matugen/scripts/gtk3_post_hook.sh'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all matugen"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/matugen/color.ini'
# post_hook = '~/.config/matugen/scripts/spiceitfy_theme_apply.sh'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen-theme'
post_hook = "if pgrep -x cava >/dev/null; then pkill -USR1 cava; fi"

[templates.ashell]
input_path = '~/.config/matugen/templates/ashell-colors.ini'
output_path = '~/.config/ashell/config.toml'

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'
# post_hook = 'pkill -SIGUSR2 ghostty'

[templates.micro]
input_path = '~/.config/matugen/templates/micro.micro'
output_path = '~/.config/micro/colorschemes/matugen.micro'

[templates.zed]
input_path = '~/.config/matugen/templates/zed-colors.json'
output_path = '~/.config/zed/themes/matugen.json'

[templates.vicinae]
input_path = '~/.config/matugen/templates/vicinae.ini'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = "if pgrep -x vicinae >/dev/null; then pkill vicinae;setsid -f vicinae server >/dev/null 2>&1; fi"
