# toggle-pane
[[mgr.prepend_keymap]]
on = "T"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

# smart-enter
[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

# wl-clipboard
[[mgr.prepend_keymap]]
on = "<C-y>"
run = ["plugin wl-clipboard"]

# confirm-quit
[[mgr.prepend_keymap]]
on = "q"
run = "plugin confirm-quit"

# yamb
[[mgr.prepend_keymap]]
on = ["b", "a"]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = ["b", "g"]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = ["b", "G"]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["b", "A"]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = ["b", "R"]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"

# projects
[[mgr.prepend_keymap]]
on = ["P", "s"]
run = "plugin projects save"
desc = "Save current project"

[[mgr.prepend_keymap]]
on = ["P", "l"]
run = "plugin projects load"
desc = "Load project"

[[mgr.prepend_keymap]]
on = ["P", "P"]
run = "plugin projects load_last"
desc = "Load last project"

[[mgr.prepend_keymap]]
on = ["P", "d"]
run = "plugin projects delete"
desc = "Delete project"

[[mgr.prepend_keymap]]
on = ["P", "D"]
run = "plugin projects delete_all"
desc = "Delete all projects"

[[mgr.prepend_keymap]]
on = ["P", "m"]
run = "plugin projects 'merge current'"
desc = "Merge current tab to other projects"

[[mgr.prepend_keymap]]
on = ["P", "M"]
run = "plugin projects 'merge all'"
desc = "Merge current project to other projects"

# ouch
[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

# diff
[[mgr.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

# zoom
[[mgr.prepend_keymap]]
on = "+"
run = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on = "-"
run = "plugin zoom -1"
desc = "Zoom out hovered file"

# vcs-files
[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "plugin vcs-files"
desc = "Show Git file changes"

# Mount
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
