[mgr]
show_hidden = true
sort_by = "alphabetical"
sort_dir_first = true
sort_sensitive = true
show_symlink = true
linemode = "size_and_mtime"

# https://yazi-rs.github.io/docs/tips/
[opener]
play = [
  { run = 'vlc "$@"', orphan = true, desc = "Open in VLC", for = "linux" },
]
edit = [{ run = '$EDITOR "$@"', block = true, for = "linux" }]

[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon -x -i -T "$0"'

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]
