[mgr]
show_hidden = true
sort_by = "alphabetical"
sort_dir_first = true
sort_sensitive = true
show_symlink = true
linemode = "size_and_mtime"

# https://yazi-rs.github.io/docs/tips/
[opener]
play = [
  { run = 'vlc --one-instance "$@"', orphan = true, desc = "Open in VLC", for = "linux" },
]
edit = [
  { run = 'kitty --class nvim fish -c "$EDITOR "$@""', orphan = true, for = "linux" },
  { run = 'gnome-text-editor "$@"', orphan = true, for = "linux" },
]


[[mgr.prepend_keymap]]
on = "<C-n>"
run = 'shell -- dragon -x -i -T "$0"'

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]

[plugin]
prepend_preloaders = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
  # Replace magick, image, video with mediainfo
  { mime = "{audio,video,image}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
  # Adobe Illustrator, Adobe Photoshop is image/adobe.photoshop, already handled above
  { mime = "application/postscript", run = "mediainfo" },
  { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch" },
]
# There are more extensions which are supported by mediainfo.
# Just add file's MIME type to `previewers`, `preloaders` above.
# https://mediaarea.net/en/MediaInfo/Support/Formats

# For a large file like Adobe Illustrator, Adobe Photoshop, etc
# you may need to increase the memory limit if no image is rendered.
# https://yazi-rs.github.io/docs/configuration/yazi#tasks
[tasks]
image_alloc = 1073741824 # = 1024*1024*1024 = 1024MB
