[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "configure"
windows = [ "ï… arch-setup", "î¯¥ dotfiles" ]

[[window]]
path = "~/projects/arch-setup/"
name = "ï… arch-setup"
startup_script = "nvim"

[[window]]
path = "~/dotfiles/"
name = "î¯¥ dotfiles"
startup_script = "nvim"
